"""add digital_twins and twin_layers

Revision ID: 103163b987c2
Revises: cad56025e1f1
Create Date: 2026-09-18 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103163b987c2'
down_revision: Union[str, None] = 'cad56025e1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_twins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digital_twins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digital_twins_project_id'), ['project_id'], unique=True)

    op.create_table('twin_layers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('twin_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('dataset_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('registered_at_version', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['twin_id'], ['digital_twins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('twin_layers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twin_layers_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_twin_layers_twin_id'), ['twin_id'], unique=False)

    # No batch_alter_table('datasets', ...) block -- unlike every prior
    # phase's migration, Phase 9 adds no column to `datasets` and no
    # circular FK: TwinLayer references Dataset, nothing on Dataset needs
    # to reference back, since Digital Twin produces no new Dataset rows.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twin_layers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twin_layers_twin_id'))
        batch_op.drop_index(batch_op.f('ix_twin_layers_dataset_id'))

    op.drop_table('twin_layers')

    with op.batch_alter_table('digital_twins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digital_twins_project_id'))

    op.drop_table('digital_twins')
    # ### end Alembic commands ###
